"""Rendered: extracted from build.py."""

import os
import sys
from pathlib import Path

from tools.index.summary_of import summary_of

HEADER = """# Brain — index

Root map of the knowledge base. Start here. The page format is documented in
SCHEMA.md in the configured brain engine checkout.

<!-- Generated by tools/index/build.py from each page's `summary:` frontmatter.
     Edit the page, not this file. -->
"""


def rendered(root: Path, directories: tuple[Path, ...], inbox: Path | None = None) -> str:
    """The whole of index.md: header, one section per folder, inbox footer.

    The footer appears only for an instance that configured an inbox: the
    unconditional one named a directory the setup never created and invented a
    next action for a reader who had no way to take it.

    A page whose `summary:` is missing or empty still gets a bullet, so the map
    never silently loses a page; its id is reported on stderr instead.
    """
    out = [HEADER]
    missing = []
    for directory in directories:
        heading = directory.name.title()
        out.append(f"## {heading}\n")
        lines = []
        for f in sorted(directory.glob("*.md")):
            page = Path(os.path.relpath(f, root)).with_suffix("").as_posix()
            summary = summary_of(f)
            if not summary:
                missing.append(page)
                lines.append(f"- [[{page}]]")
                continue
            lines.append(f"- [[{page}]] — {summary}")
        out.append("\n".join(lines) + "\n")
    if missing:
        for page in missing:
            print(f"no summary: {page}", file=sys.stderr)
    if inbox is not None:
        name = Path(os.path.relpath(inbox, root)).as_posix()
        out.append(
            f"---\n\n**Inbox:** `{name}/` receives captured clips; ingest them with clips.\n"
        )
    return "\n".join(out) + "\n"
