"""Rendered: extracted from build.py."""

import os
import sys
from pathlib import Path

from tools.index.summary_of import summary_of

HEADER = """# Brain — index

Root map of the knowledge base. Start here. See [[SCHEMA]] for how it works.

<!-- Generated by tools/index/build.py from each page's `summary:` frontmatter.
     Edit the page, not this file. -->
"""

FOOTER = """---

**Inbox:** `inbox/` is empty. Drop files there to ingest.
"""


def rendered(root: Path, directories: tuple[Path, ...]) -> str:
    """The whole of index.md: header, one section per folder, inbox footer.

    A page whose `summary:` is missing or empty still gets a bullet, so the map
    never silently loses a page; its id is reported on stderr instead.
    """
    out = [HEADER]
    missing = []
    for directory in directories:
        heading = directory.name.title()
        out.append(f"## {heading}\n")
        lines = []
        for f in sorted(directory.glob("*.md")):
            page = Path(os.path.relpath(f, root)).with_suffix("").as_posix()
            summary = summary_of(f)
            if not summary:
                missing.append(page)
                lines.append(f"- [[{page}]]")
                continue
            lines.append(f"- [[{page}]] — {summary}")
        out.append("\n".join(lines) + "\n")
    if missing:
        for page in missing:
            print(f"no summary: {page}", file=sys.stderr)
    return "\n".join(out) + "\n" + FOOTER
